services:
  graphql:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}