services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial-scraper
    ports:
      - "5432:5432"
  graphql:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/financial-scraper